seungjae93/finalproject

src/components/MyCommunity.jsx, src/components/MyReview.jsx, src/components/PostCode.js, src/pages/Mypage.jsx, src/pages/Review.jsx, src/redux/api/mypageApi.js, src/redux/api/reviewApi.js, src/shared/Router.js
마이페이지에서 작성한 리뷰와 게시글 불러오기 기능 구현
=> :sparkles:feat:마이페이지 기능 구현

src/components/Header.js, src/hooks/useCheckLogin.js, src/pages/Comment.jsx, src/pages/PostCommunity/PostDetail.jsx, src/pages/PostCommunity/PostList.jsx, src/redux/api/communityApi.js, src/redux/modules/kakaoSlice.js
⚡  fix: 커뮤니티,댓글 작성하기, 수정하기, 삭제하기 닉네임이 일치하기 않을때 사라지게 하는 예외처리
=> ⚡  fix: 로그인 예외처리

src/components/Header.js
⚡  fix: localstorage 삭제가 안되서 새롭게 삭제 구현
=> ⚡  fix:localstoage삭제

src/components/Map/ServeReviewModal.jsx, src/components/Map/TotalReview.jsx, src/pages/MainMap.jsx
=> ✨ feat: 클러스터러 기능 구현

src/components/Header.jsx, src/components/Map/ServeReviewModal.jsx, src/components/Map/TotalReview.jsx, src/pages/MainMap.jsx
:sparkles: feat: 검색어 클릭시 input값 변환 완료
=> :sparkles: feat: 검색어 클릭시 input값 변환 완료

src/components/Map/ServeReviewModal.jsx, src/pages/PostCommunity/PostList.jsx
⚡  fix: map 상세보기를 클릭하고 그 안에서 한번 더 모달이 나오는 부분에서 모든 모달이 나오는 오류가 생겨 하나씩 나오게 수정했음, 
fix : 커뮤니티 기능에서 제목만 검색이 아닌 내용도 검색이 가능
=> ⚡  fix: map 상세보기 모달 오류 수정

src/components/Community/PostForm.jsx, src/components/Community/PostListCard.jsx, src/components/Map/ServeReviewModal.jsx, src/pages/PostCommunity/PostDetail.jsx, src/pages/PostCommunity/PostEdit.jsx, src/pages/PostCommunity/PostInfiniteScroll.jsx, src/redux/api/communityApi.js
🐛  fix: detail modal에서 박스를 클릭했을 때 닫히지 않는 현상 해결
=> 🐛  fix: detail modal 버그 수정

src/pages/Review.jsx
:ambulance: fix: 우편주소 api 토글식으로 변경
=> :ambulance: fix: 우편주소 api 토글식으로 변경

package-lock.json, package.json, src/pages/PostCommunity/PostList.jsx, src/redux/api/communityApi.js
⚡  refactor: 커뮤니티 게시판 전에는 프론트 단에서 filter와 sort로 해결했던 문제들을 전체적으로 수정 
API요청을 통해서 구현할 수 있게 모든 포직 변경
=> ⚡  refactor: 커뮤니티 게시판 리펙토링

package-lock.json, package.json, src/components/Header.jsx, src/components/MyCommunity.jsx, src/components/MyReview.jsx, src/pages/MainPage.jsx, src/pages/Review.jsx, src/redux/api/mypageApi.js, src/redux/api/reviewApi.js
메인페이지, 마이페이지, 리뷰작성 페이지 CSS 수정작업
=> :lipstick:fix:전반적인 CSS 수정작업 

src/components/Community/PostForm.jsx, src/components/Community/PostListCard.jsx, src/hooks/useCheckLogin.js, src/pages/Comment.jsx, src/pages/PostCommunity/PostEdit.jsx, src/pages/PostCommunity/PostList.jsx, src/redux/api/communityApi.js
💄  fix: 전체적인 축소 형태였을 때 무너지는 css 상태 정리 및 수정
=> 💄  fix: style 수정

src/components/Header.jsx, src/pages/ReviewPage.jsx
=> :art:fix:리뷰 유효성 검사 로직구현 및 CSS 일부 수정

src/components/Map/ServeReviewModal.jsx
💄 fix: serveReviewModal css 수정
=> 💄 fix: serveReviewModal css 수정

public/index.html, src/components/Map/ServeReviewModal.jsx
=> ✨  feat: favicon 추가

src/components/mypage/MyReview.jsx, src/pages/MainMap.jsx
=> 🎨  fix: 지도 초기 위치 수정

src/pages/PostCommunity/PostList.jsx, src/redux/modules/kakaoSlice.js
=> ⚡  fix:커뮤니티 오류, 로그인 등 수정

src/components/Community/PostForm.jsx, src/components/styles/GlobalStyle.jsx, src/pages/KakaoLogin.jsx, src/pages/PostCommunity/PostDetail.jsx, src/pages/PostCommunity/PostList.jsx
🎨  fix:커뮤니티 게시글 지역선택에서 포스트 없이 오류 나오는 부분 수정
=> 🎨  fix:커뮤니티 게시글 오류 수정

src/components/Header.jsx, src/pages/Comment.jsx
=> 🎨  fix: 댓글작성란 CSS수정

src/pages/KakaoLogin.jsx, src/redux/modules/kakaoSlice.js
🐛  fix:로그인 에서 알럿창이 어색하게 나오는 부분 수정
=> 🐛  fix:로그인 알럿 수정

src/components/mypage/MyCommunity.jsx, src/components/mypage/MyReview.jsx, src/pages/Mypage.jsx, src/pages/PostCommunity/PostDetail.jsx
=> 💄  fix: mypage CSS 수정

src/components/Community/Radio.jsx, src/hooks/useInputItem.js, src/pages/ReviewPage.jsx
=> ♻️  fix: 후기작성 페이지 리펙토링

src/components/mypage/MyCommunity.jsx, src/pages/ReviewPage.jsx
=> ♻️  fix: 전체 코드 리펙토링

src/components/Community/KakaoAddress.jsx, src/components/Community/Radio.jsx, src/pages/ReviewPage.jsx
=> ♻️  fix:카카오 주소 리펙토링

src/components/Footer.jsx, src/pages/KakaoLogin.jsx
=> 🐛  fix:카카오 알럿 오류

src/components/Community/NextPreviousPost.jsx, src/components/Community/PostListCard.jsx, src/pages/Mypage.jsx, src/pages/PostCommunity/PostDetail.jsx, src/shared/Router.js
=> 🐛  fix:뒤로가기 수정

src/components/Community/PostListCard.jsx, src/pages/Mypage.jsx
=> 🐛  fix:뒤로가기 추가 수정

src/components/Community/PostForm.jsx
🐛  fix: 마이페이지와 글쓰기 페이지에서 로그아웃 했는데도 불구하구 뒤로가기 했을 때 해당 페이지 접속되는 문제 해결
=> 🐛  fix:뒤로가기 추가수정

src/components/Map/ReviewList.jsx
♻️ refactor: ReviewList useMemo 리팩토링
💄 style: css 구조 개선
=> ♻️ refactor: ReviewList 리팩토링

src/components/Community/PostForm.jsx
=> 🐛 fix: URL직접 접근 제어
